baseURL = "https://jackiebinya.github.io"
languageCode = "en-us"
title = "Jacqueline Binya"
theme = "anubis"
paginate = 3

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Jacqueline Binya"

[params]
   author = "Jacqueline Binya"
   # description = "Anubis is a simple minimalist theme for Hugo blog engine."

[menu]

  [[menu.main]]
    identifier = "about"
    name = "ðŸ“–readme"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "archive"
    name = "ðŸ“°blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "ðŸ“‘projects"
    identifier = "projects"
    url = "/projects/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"